#! /bin/sh

if [ ! -n "${DBMANUL_HOME+x}" ]; then
  # echo "DBMANUL_HOME is not set."

  ## resolve links - $0 may be a symlink
  PRG="$0"
  while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
  done


  DBMANUL_HOME=`dirname "$PRG"`

  # make it fully qualified
  DBMANUL_HOME=`cd "$DBMANUL_HOME" && pwd`
  # echo "DB-Manul Home: $DBMANUL_HOME"
fi

 
# build classpath from all jars in lib
if [ -f /usr/bin/cygpath ]; then
  CP=.
  for i in "$DBMANUL_HOME"/dbmanul*.jar; do
    i=`cygpath --windows "$i"`
    CP="$CP;$i"
  done
  for i in "$DBMANUL_HOME"/lib/*.jar; do
    i=`cygpath --windows "$i"`
    CP="$CP;$i"
  done
else
  CP=.
  for i in "$DBMANUL_HOME"/dbmanul*.jar; do
    CP="$CP":"$i"
  done
  for i in "$DBMANUL_HOME"/lib/*.jar; do
    CP="$CP":"$i"
  done
fi

# add any JVM options here
JAVA_OPTS=

java -cp "$CP" $JAVA_OPTS dbmanul.integration.commandline.Main ${1+"$@"}


