package liquibase.sqlgenerator;

import liquibase.database.Database;
import liquibase.database.H2Database;
import liquibase.statement.AddAutoIncrementStatement;
import org.junit.Test;

public class AddAutoIncrementGeneratorHsqlTest extends AddAutoIncrementGeneratorTest<AddAutoIncrementStatement> {

    public AddAutoIncrementGeneratorHsqlTest() throws Exception {
    	super(new AddAutoIncrementGeneratorHsql());
    }

    @Test
    public void generateSql_noSchema() throws Exception {
//        testSqlOnAll("ALTER TABLE [table_name] ALTER COLUMN [id] int GENERATED BY DEFAULT AS IDENTITY IDENTITY", new AddAutoIncrementStatement(null, "table_name", "id", "int"));
        testSqlOnAll(null, new AddAutoIncrementStatement(null, "table_name", "id", "int"));
    }

    @Override
    protected boolean shouldBeImplementation(Database database) {
        return database instanceof H2Database;
    }
}