CREATE TABLE [dbo].[dataTypeTestTIME](
	[TIME_NULL] [time](7) NULL,
	[TIME_NOTNULL] [time](7) NOT NULL,
	[TIME_DEFAULT] [time](7) NULL,
	[TIME_PK] [time](7) NOT NULL,
	[TIME_UNIQUE] [time](7) NULL,
 CONSTRAINT [PK_time] PRIMARY KEY CLUSTERED
(
	[TIME_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_time] UNIQUE NONCLUSTERED
(
	[TIME_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestNTEXT](
	[NTEXT_NULL] [ntext] NULL,
	[NTEXT_NOTNULL] [ntext] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestDATE](
	[DATE_NULL] [date] NULL,
	[DATE_NOTNULL] [date] NOT NULL,
	[DATE_DEFAULT] [date] NULL,
	[DATE_PK] [date] NOT NULL,
	[DATE_UNIQUE] [date] NULL,
 CONSTRAINT [PK_date] PRIMARY KEY CLUSTERED
(
	[DATE_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_date] UNIQUE NONCLUSTERED
(
	[DATE_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestTEXT](
	[TEXT_NULL] [text] NULL,
	[TEXT_NOTNULL] [text] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestVARBINARY](
	[VARBINARY_NULL] [varbinary](1) NULL,
	[VARBINARY_NOTNULL] [varbinary](1) NOT NULL,
	[VARBINARY_DEFAULT] [varbinary](1) NULL,
	[VARBINARY_PK] [varbinary](1) NOT NULL,
	[VARBINARY_UNIQUE] [varbinary](1) NULL,
	[VARBINARY_MAX] [varbinary](MAX) NULL,
 CONSTRAINT [PK_varbinary] PRIMARY KEY CLUSTERED
(
	[VARBINARY_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_varbinary] UNIQUE NONCLUSTERED
(
	[VARBINARY_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO