CREATE TABLE [dbo].[dataTypeTestXML](
  [XML_NULL]    [XML] NULL,
  [XML_NOTNULL] [XML] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestSMALLMONEY](
  [SMALLMONEY_NULL]    [SMALLMONEY] NULL,
  [SMALLMONEY_NOTNULL] [SMALLMONEY] NOT NULL,
  [SMALLMONEY_DEFAULT] [SMALLMONEY] NULL,
  [SMALLMONEY_PK]      [SMALLMONEY] NOT NULL,
  [SMALLMONEY_UNIQUE]  [SMALLMONEY] NULL,
 CONSTRAINT [PK_smallmoney] PRIMARY KEY CLUSTERED
(
  [SMALLMONEY_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_smallmoney] UNIQUE NONCLUSTERED
(
  [SMALLMONEY_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestHIERARCHYID](
  [HIERARCHYID_NULL]    [HIERARCHYID] NULL,
  [HIERARCHYID_NOTNULL] [HIERARCHYID] NOT NULL,
  [HIERARCHYID_PK]      [HIERARCHYID] NOT NULL,
  [HIERARCHYID_UNIQUE]  [HIERARCHYID] NULL,
 CONSTRAINT [PK_hierarchyid] PRIMARY KEY CLUSTERED
(
  [HIERARCHYID_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_hierarchyid] UNIQUE NONCLUSTERED
(
  [HIERARCHYID_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestIMAGE](
  [IMAGE_NULL]    [IMAGE] NULL,
  [IMAGE_NOTNULL] [IMAGE] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestDATETIME2](
  [DATETIME2_NULL]    [DATETIME2](7) NULL,
  [DATETIME2_NOTNULL] [DATETIME2](7) NOT NULL,
  [DATETIME2_DEFAULT] [DATETIME2](7) NULL,
  [DATETIME2_PK]      [DATETIME2](7) NOT NULL,
  [DATETIME2_UNIQUE]  [DATETIME2](7) NULL,
 CONSTRAINT [PK_datetime2] PRIMARY KEY CLUSTERED
(
  [DATETIME2_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_datetime2] UNIQUE NONCLUSTERED
(
  [DATETIME2_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestDATETIMEOFFSET](
  [DATETIMEOFFSET_NULL]    [DATETIMEOFFSET](7) NULL,
  [DATETIMEOFFSET_NOTNULL] [DATETIMEOFFSET](7) NOT NULL,
  [DATETIMEOFFSET_DEFAULT] [DATETIMEOFFSET](7) NULL,
  [DATETIMEOFFSET_PK]      [DATETIMEOFFSET](7) NOT NULL,
  [DATETIMEOFFSET_UNIQUE]  [DATETIMEOFFSET](7) NULL,
 CONSTRAINT [PK_datetimeoffset] PRIMARY KEY CLUSTERED
(
  [DATETIMEOFFSET_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_datetimeoffset] UNIQUE NONCLUSTERED
(
  [DATETIMEOFFSET_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
