CREATE TABLE [dbo].[dataTypeTestTIME](
  [TIME_NULL]    [TIME](7) NULL,
  [TIME_NOTNULL] [TIME](7) NOT NULL,
  [TIME_DEFAULT] [TIME](7) NULL,
  [TIME_PK]      [TIME](7) NOT NULL,
  [TIME_UNIQUE]  [TIME](7) NULL,
 CONSTRAINT [PK_time] PRIMARY KEY CLUSTERED
(
  [TIME_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_time] UNIQUE NONCLUSTERED
(
  [TIME_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestNTEXT](
  [NTEXT_NULL]    [NTEXT] NULL,
  [NTEXT_NOTNULL] [NTEXT] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestDATE](
  [DATE_NULL]    [DATE] NULL,
  [DATE_NOTNULL] [DATE] NOT NULL,
  [DATE_DEFAULT] [DATE] NULL,
  [DATE_PK]      [DATE] NOT NULL,
  [DATE_UNIQUE]  [DATE] NULL,
 CONSTRAINT [PK_date] PRIMARY KEY CLUSTERED
(
  [DATE_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_date] UNIQUE NONCLUSTERED
(
  [DATE_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestTEXT](
  [TEXT_NULL]    [TEXT] NULL,
  [TEXT_NOTNULL] [TEXT] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestVARBINARY](
  [VARBINARY_NULL]    [VARBINARY](1)   NULL,
  [VARBINARY_NOTNULL] [VARBINARY](1)   NOT NULL,
  [VARBINARY_DEFAULT] [VARBINARY](1)   NULL,
  [VARBINARY_PK]      [VARBINARY](1)   NOT NULL,
  [VARBINARY_UNIQUE]  [VARBINARY](1)   NULL,
  [VARBINARY_MAX]     [VARBINARY](MAX) NULL,
 CONSTRAINT [PK_varbinary] PRIMARY KEY CLUSTERED
(
  [VARBINARY_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_varbinary] UNIQUE NONCLUSTERED
(
  [VARBINARY_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO