CREATE TABLE [dbo].[dataTypeTestXML](
	[XML_NULL] [xml] NULL,
	[XML_NOTNULL] [xml] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestSMALLMONEY](
	[SMALLMONEY_NULL] [smallmoney] NULL,
	[SMALLMONEY_NOTNULL] [smallmoney] NOT NULL,
	[SMALLMONEY_DEFAULT] [smallmoney] NULL,
	[SMALLMONEY_PK] [smallmoney] NOT NULL,
	[SMALLMONEY_UNIQUE] [smallmoney] NULL,
 CONSTRAINT [PK_smallmoney] PRIMARY KEY CLUSTERED
(
	[SMALLMONEY_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_smallmoney] UNIQUE NONCLUSTERED
(
	[SMALLMONEY_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestHIERARCHYID](
	[HIERARCHYID_NULL] [hierarchyid] NULL,
	[HIERARCHYID_NOTNULL] [hierarchyid] NOT NULL,
	[HIERARCHYID_PK] [hierarchyid] NOT NULL,
	[HIERARCHYID_UNIQUE] [hierarchyid] NULL,
 CONSTRAINT [PK_hierarchyid] PRIMARY KEY CLUSTERED
(
	[HIERARCHYID_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_hierarchyid] UNIQUE NONCLUSTERED
(
	[HIERARCHYID_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestIMAGE](
	[IMAGE_NULL] [image] NULL,
	[IMAGE_NOTNULL] [image] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestDATETIME2](
	[DATETIME2_NULL] [datetime2](7) NULL,
	[DATETIME2_NOTNULL] [datetime2](7) NOT NULL,
	[DATETIME2_DEFAULT] [datetime2](7) NULL,
	[DATETIME2_PK] [datetime2](7) NOT NULL,
	[DATETIME2_UNIQUE] [datetime2](7) NULL,
 CONSTRAINT [PK_datetime2] PRIMARY KEY CLUSTERED
(
	[DATETIME2_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_datetime2] UNIQUE NONCLUSTERED
(
	[DATETIME2_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestDATETIMEOFFSET](
	[DATETIMEOFFSET_NULL] [datetimeoffset](7) NULL,
	[DATETIMEOFFSET_NOTNULL] [datetimeoffset](7) NOT NULL,
	[DATETIMEOFFSET_DEFAULT] [datetimeoffset](7) NULL,
	[DATETIMEOFFSET_PK] [datetimeoffset](7) NOT NULL,
	[DATETIMEOFFSET_UNIQUE] [datetimeoffset](7) NULL,
 CONSTRAINT [PK_datetimeoffset] PRIMARY KEY CLUSTERED
(
	[DATETIMEOFFSET_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_datetimeoffset] UNIQUE NONCLUSTERED
(
	[DATETIMEOFFSET_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
