CREATE TABLE [dbo].[dataTypeTestBIGINT](
	[BIGINT_NULL] [bigint] NULL,
	[BIGINT_NOTNULL] [bigint] NOT NULL,
	[BIGINT_DEFAULT] [bigint] NULL,
	[BIGINT_PK] [bigint] NOT NULL,
	[BIGINT_UNIQUE] [bigint] NULL,
	[BIGINT_AUTOINCREMENT] [bigint] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_bigint] PRIMARY KEY CLUSTERED
(
	[BIGINT_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_bigint] UNIQUE NONCLUSTERED
(
	[BIGINT_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestBINARY](
	[BINARY_NULL] [binary](1) NULL,
	[BINARY_NOTNULL] [binary](1) NOT NULL,
	[BINARY_DEFAULT] [binary](1) NULL,
	[BINARY_PK] [binary](1) NOT NULL,
	[BINARY_UNIQUE] [binary](1) NULL,
 CONSTRAINT [PK_binary] PRIMARY KEY CLUSTERED
(
	[BINARY_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_binary] UNIQUE NONCLUSTERED
(
	[BINARY_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestBIT](
	[BIT_NULL] [bit] NULL,
	[BIT_NOTNULL] [bit] NOT NULL,
	[BIT_DEFAULT] [bit] NULL,
	[BIT_PK] [bit] NOT NULL,
	[BIT_UNIQUE] [bit] NULL,
 CONSTRAINT [PK_bit] PRIMARY KEY CLUSTERED
(
	[BIT_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_bit] UNIQUE NONCLUSTERED
(
	[BIT_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestCHAR](
	[CHAR_NULL] [char](1) NULL,
	[CHAR_NOTNULL] [char](1) NOT NULL,
	[CHAR_DEFAULT] [char](1) NULL,
	[CHAR_PK] [char](1) NOT NULL,
	[CHAR_UNIQUE] [char](1) NULL,
 CONSTRAINT [PK_char] PRIMARY KEY CLUSTERED
(
	[CHAR_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_char] UNIQUE NONCLUSTERED
(
	[CHAR_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestDATE](
	[DATE_NULL] [date] NULL,
	[DATE_NOTNULL] [date] NOT NULL,
	[DATE_DEFAULT] [date] NULL,
	[DATE_PK] [date] NOT NULL,
	[DATE_UNIQUE] [date] NULL,
 CONSTRAINT [PK_date] PRIMARY KEY CLUSTERED
(
	[DATE_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_date] UNIQUE NONCLUSTERED
(
	[DATE_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestDATETIME](
	[DATETIME_NULL] [datetime] NULL,
	[DATETIME_NOTNULL] [datetime] NOT NULL,
	[DATETIME_DEFAULT] [datetime] NULL,
	[DATETIME_PK] [datetime] NOT NULL,
	[DATETIME_UNIQUE] [datetime] NULL,
 CONSTRAINT [PK_datetime] PRIMARY KEY CLUSTERED
(
	[DATETIME_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_datetime] UNIQUE NONCLUSTERED
(
	[DATETIME_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestDATETIME2](
	[DATETIME2_NULL] [datetime2](7) NULL,
	[DATETIME2_NOTNULL] [datetime2](7) NOT NULL,
	[DATETIME2_DEFAULT] [datetime2](7) NULL,
	[DATETIME2_PK] [datetime2](7) NOT NULL,
	[DATETIME2_UNIQUE] [datetime2](7) NULL,
 CONSTRAINT [PK_datetime2] PRIMARY KEY CLUSTERED
(
	[DATETIME2_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_datetime2] UNIQUE NONCLUSTERED
(
	[DATETIME2_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestDATETIMEOFFSET](
	[DATETIMEOFFSET_NULL] [datetimeoffset](7) NULL,
	[DATETIMEOFFSET_NOTNULL] [datetimeoffset](7) NOT NULL,
	[DATETIMEOFFSET_DEFAULT] [datetimeoffset](7) NULL,
	[DATETIMEOFFSET_PK] [datetimeoffset](7) NOT NULL,
	[DATETIMEOFFSET_UNIQUE] [datetimeoffset](7) NULL,
 CONSTRAINT [PK_datetimeoffset] PRIMARY KEY CLUSTERED
(
	[DATETIMEOFFSET_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_datetimeoffset] UNIQUE NONCLUSTERED
(
	[DATETIMEOFFSET_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestDECIMAL](
	[DECIMAL_NULL] [decimal](18, 0) NULL,
	[DECIMAL_NOTNULL] [decimal](18, 0) NOT NULL,
	[DECIMAL_DEFAULT] [decimal](18, 0) NULL,
	[DECIMAL_PK] [decimal](18, 0) NOT NULL,
	[DECIMAL_UNIQUE] [decimal](18, 0) NULL,
	[DECIMAL_AUTOINCREMENT] [decimal](18, 0) IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_decimal] PRIMARY KEY CLUSTERED
(
	[DECIMAL_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_decimal] UNIQUE NONCLUSTERED
(
	[DECIMAL_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestFLOAT](
	[FLOAT_NULL] [float] NULL,
	[FLOAT_NOTNULL] [float] NOT NULL,
	[FLOAT_DEFAULT] [float] NULL,
	[FLOAT_PK] [float] NOT NULL,
	[FLOAT_UNIQUE] [float] NULL,
 CONSTRAINT [PK_float] PRIMARY KEY CLUSTERED
(
	[FLOAT_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_float] UNIQUE NONCLUSTERED
(
	[FLOAT_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestINT](
	[INT_NULL] [int] NULL,
	[INT_NOTNULL] [int] NOT NULL,
	[INT_DEFAULT] [int] NULL,
	[INT_PK] [int] NOT NULL,
	[INT_UNIQUE] [int] NULL,
	[INT_AUTOINCREMENT] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_int] PRIMARY KEY CLUSTERED
(
	[INT_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_int] UNIQUE NONCLUSTERED
(
	[INT_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestMONEY](
	[MONEY_NULL] [money] NULL,
	[MONEY_NOTNULL] [money] NOT NULL,
	[MONEY_DEFAULT] [money] NULL,
	[MONEY_PK] [money] NOT NULL,
	[MONEY_UNIQUE] [money] NULL,
 CONSTRAINT [PK_money] PRIMARY KEY CLUSTERED
(
	[MONEY_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_money] UNIQUE NONCLUSTERED
(
	[MONEY_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestNCHAR](
	[NCHAR_NULL] [nchar](1) NULL,
	[NCHAR_NOTNULL] [nchar](1) NOT NULL,
	[NCHAR_DEFAULT] [nchar](1) NULL,
	[NCHAR_PK] [nchar](1) NOT NULL,
	[NCHAR_UNIQUE] [nchar](1) NULL,
 CONSTRAINT [PK_nchar] PRIMARY KEY CLUSTERED
(
	[NCHAR_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_nchar] UNIQUE NONCLUSTERED
(
	[NCHAR_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestNUMERIC](
	[NUMERIC_NULL] [numeric](18, 0) NULL,
	[NUMERIC_NOTNULL] [numeric](18, 0) NOT NULL,
	[NUMERIC_DEFAULT] [numeric](18, 0) NULL,
	[NUMERIC_PK] [numeric](18, 0) NOT NULL,
	[NUMERIC_UNIQUE] [numeric](18, 0) NULL,
	[NUMERIC_AUTOINCREMENT] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_numeric] PRIMARY KEY CLUSTERED
(
	[NUMERIC_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_numeric] UNIQUE NONCLUSTERED
(
	[NUMERIC_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestNVARCHAR](
	[NVARCHAR_NULL] [nvarchar](1) NULL,
	[NVARCHAR_NOTNULL] [nvarchar](1) NOT NULL,
	[NVARCHAR_DEFAULT] [nvarchar](1) NULL,
	[NVARCHAR_PK] [nvarchar](1) NOT NULL,
	[NVARCHAR_UNIQUE] [nvarchar](1) NULL,
 CONSTRAINT [PK_nvarchar] PRIMARY KEY CLUSTERED
(
	[NVARCHAR_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_nvarchar] UNIQUE NONCLUSTERED
(
	[NVARCHAR_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestREAL](
	[REAL_NULL] [real] NULL,
	[REAL_NOTNULL] [real] NOT NULL,
	[REAL_DEFAULT] [real] NULL,
	[REAL_PK] [real] NOT NULL,
	[REAL_UNIQUE] [real] NULL,
 CONSTRAINT [PK_real] PRIMARY KEY CLUSTERED
(
	[REAL_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_real] UNIQUE NONCLUSTERED
(
	[REAL_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestSMALLDATETIME](
	[SMALLDATETIME_NULL] [smalldatetime] NULL,
	[SMALLDATETIME_NOTNULL] [smalldatetime] NOT NULL,
	[SMALLDATETIME_DEFAULT] [smalldatetime] NULL,
	[SMALLDATETIME_PK] [smalldatetime] NOT NULL,
	[SMALLDATETIME_UNIQUE] [smalldatetime] NULL,
 CONSTRAINT [PK_smalldatetime] PRIMARY KEY CLUSTERED
(
	[SMALLDATETIME_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_smalldatetime] UNIQUE NONCLUSTERED
(
	[SMALLDATETIME_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestSMALLINT](
	[SMALLINT_NULL] [smallint] NULL,
	[SMALLINT_NOTNULL] [smallint] NOT NULL,
	[SMALLINT_DEFAULT] [smallint] NULL,
	[SMALLINT_PK] [smallint] NOT NULL,
	[SMALLINT_UNIQUE] [smallint] NULL,
	[SMALLINT_AUTOINCREMENT] [smallint] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_smallint] PRIMARY KEY CLUSTERED
(
	[SMALLINT_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_smallint] UNIQUE NONCLUSTERED
(
	[SMALLINT_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestSMALLMONEY](
	[SMALLMONEY_NULL] [smallmoney] NULL,
	[SMALLMONEY_NOTNULL] [smallmoney] NOT NULL,
	[SMALLMONEY_DEFAULT] [smallmoney] NULL,
	[SMALLMONEY_PK] [smallmoney] NOT NULL,
	[SMALLMONEY_UNIQUE] [smallmoney] NULL,
 CONSTRAINT [PK_smallmoney] PRIMARY KEY CLUSTERED
(
	[SMALLMONEY_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_smallmoney] UNIQUE NONCLUSTERED
(
	[SMALLMONEY_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestTIME](
	[TIME_NULL] [time](7) NULL,
	[TIME_NOTNULL] [time](7) NOT NULL,
	[TIME_DEFAULT] [time](7) NULL,
	[TIME_PK] [time](7) NOT NULL,
	[TIME_UNIQUE] [time](7) NULL,
 CONSTRAINT [PK_time] PRIMARY KEY CLUSTERED
(
	[TIME_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_time] UNIQUE NONCLUSTERED
(
	[TIME_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestTINYINT](
	[TINYINT_NULL] [tinyint] NULL,
	[TINYINT_NOTNULL] [tinyint] NOT NULL,
	[TINYINT_DEFAULT] [tinyint] NULL,
	[TINYINT_PK] [tinyint] NOT NULL,
	[TINYINT_UNIQUE] [tinyint] NULL,
	[TINYINT_AUTOINCREMENT] [tinyint] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_tinyint] PRIMARY KEY CLUSTERED
(
	[TINYINT_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_tinyint] UNIQUE NONCLUSTERED
(
	[TINYINT_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[dataTypeTestVARBINARY](
	[VARBINARY_NULL] [varbinary](1) NULL,
	[VARBINARY_NOTNULL] [varbinary](1) NOT NULL,
	[VARBINARY_DEFAULT] [varbinary](1) NULL,
	[VARBINARY_PK] [varbinary](1) NOT NULL,
	[VARBINARY_UNIQUE] [varbinary](1) NULL,
 CONSTRAINT [PK_varbinary] PRIMARY KEY CLUSTERED
(
	[VARBINARY_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_varbinary] UNIQUE NONCLUSTERED
(
	[VARBINARY_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[dataTypeTestVARCHAR](
	[VARCHAR_NULL] [varchar](1) NULL,
	[VARCHAR_NOTNULL] [varchar](1) NOT NULL,
	[VARCHAR_DEFAULT] [varchar](1) NULL,
	[VARCHAR_PK] [varchar](1) NOT NULL,
	[VARCHAR_UNIQUE] [varchar](1) NULL,
 CONSTRAINT [PK_varchar] PRIMARY KEY CLUSTERED
(
	[VARCHAR_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UN_varchar] UNIQUE NONCLUSTERED
(
	[VARCHAR_UNIQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[dataTypeTestBIGINT] ADD  DEFAULT ((1)) FOR [BIGINT_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestBINARY] ADD  DEFAULT ((1)) FOR [BINARY_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestBIT] ADD  DEFAULT ((1)) FOR [BIT_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestCHAR] ADD  DEFAULT ((1)) FOR [CHAR_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestDATE] ADD  DEFAULT ('2017-12-09') FOR [DATE_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestDATETIME] ADD  DEFAULT ('2017-12-09T23:52:39.123') FOR [DATETIME_DEFAULT]
GO
-- Should trigger a warning because the date-format is ambiguous.
ALTER TABLE [dbo].[dataTypeTestDATETIME2] ADD  DEFAULT ('2017-12-09 23:52:39.1234567') FOR [DATETIME2_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestDATETIMEOFFSET] ADD  DEFAULT ('2017-12-09 23:52:39.1234567 +01:00') FOR [DATETIMEOFFSET_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestDECIMAL] ADD  DEFAULT ((1)) FOR [DECIMAL_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestFLOAT] ADD  DEFAULT ((1)) FOR [FLOAT_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestINT] ADD  DEFAULT ((1)) FOR [INT_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestMONEY] ADD  DEFAULT ((1)) FOR [MONEY_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestNCHAR] ADD  DEFAULT ((1)) FOR [NCHAR_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestNUMERIC] ADD  DEFAULT ((1)) FOR [NUMERIC_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestNVARCHAR] ADD  DEFAULT ((1)) FOR [NVARCHAR_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestREAL] ADD  DEFAULT ((1)) FOR [REAL_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestSMALLDATETIME] ADD  DEFAULT ('2017-12-09 23:52:39') FOR [SMALLDATETIME_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestSMALLINT] ADD  DEFAULT ((1)) FOR [SMALLINT_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestSMALLMONEY] ADD  DEFAULT ((1)) FOR [SMALLMONEY_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestTIME] ADD  DEFAULT ('23:52:39') FOR [TIME_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestTINYINT] ADD  DEFAULT ((1)) FOR [TINYINT_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestVARBINARY] ADD  DEFAULT ((1)) FOR [VARBINARY_DEFAULT]
GO
ALTER TABLE [dbo].[dataTypeTestVARCHAR] ADD  DEFAULT ((1)) FOR [VARCHAR_DEFAULT]
GO