-- Database: db2i
-- Change Parameter: columnDataType=int
-- Database: db2i
-- Change Parameter: columnName=id
-- Database: db2i
-- Change Parameter: tableName=person
ALTER TABLE person ALTER COLUMN id SET GENERATED BY DEFAULT AS IDENTITY;
