-- Database: unsupported
-- Change Parameter: columnDataType=int
-- Database: unsupported
-- Change Parameter: columnName=id
-- Database: unsupported
-- Change Parameter: tableName=person
ALTER TABLE person MODIFY id int GENERATED BY DEFAULT AS IDENTITY;
