package liquibase.database.statement.generator;

import org.junit.Test;
import liquibase.database.statement.AddAutoIncrementStatement;
import liquibase.database.Database;
import liquibase.database.HsqlDatabase;
import liquibase.database.H2Database;

public class AddAutoIncrementGeneratorH2Test extends AddAutoIncrementGeneratorTest {

    public AddAutoIncrementGeneratorH2Test() {
        super(new AddAutoIncrementGeneratorH2());
    }

    @Test
    public void generateSql_noSchema() throws Exception {
//        testSqlOnAll("ALTER TABLE [table_name] ALTER COLUMN [id] int GENERATED BY DEFAULT AS IDENTITY IDENTITY", new AddAutoIncrementStatement(null, "table_name", "id", "int"));
        testSqlOnAll(null, new AddAutoIncrementStatement(null, "table_name", "id", "int"));
    }

    @Override
    protected boolean shouldBeImplementation(Database database) {
        return database instanceof H2Database;
    }
}