/* Generated By:JavaCC: Do not edit this line. SimpleSqlGrammarConstants.java */
package liquibase.util.grammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleSqlGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 3;
  /** RegularExpression Id. */
  int S_DOUBLE = 4;
  /** RegularExpression Id. */
  int S_LONG = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int COMPLEX_IDENTIFIER = 7;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 8;
  /** RegularExpression Id. */
  int LETTER = 9;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 10;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 11;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 12;
  /** RegularExpression Id. */
  int EMPTY_QUOTE = 13;
  /** RegularExpression Id. */
  int ADDITIONAL_LETTERS = 14;
  /** RegularExpression Id. */
  int SYMBOL = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_DOUBLE>",
    "<S_LONG>",
    "<DIGIT>",
    "<COMPLEX_IDENTIFIER>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "<EMPTY_QUOTE>",
    "<ADDITIONAL_LETTERS>",
    "<SYMBOL>",
  };

}
