.\" Manpage for liquibase.
.\" Contact adrien.sales@gmail.com to correct errors or typos.
.TH man 8 "17 June 2014" "1.0" "liquibase man page"
.SH NAME
liquibase \- Database version control software
.SH SYNOPSIS
liquibase --help
.SH DESCRIPTION
Liquibase is an open source database-independent library for tracking, managing and applying database schema changes. It was started in 2006 to allow easier tracking of database changes, especially in an agile software development environment.
.SH OPTIONS
The liquibase takes a lot of arguments and options. Just run liquibase --help to get all of them.
To get full command line documentation, take a look at http://www.liquibase.org/documentation/command_line.html
.SH BUGS
To get an exact view on known bugs/features, take a look at https://liquibase.jira.com/
.SH AUTHOR
Adrien.Sales (adrien.sales@gmail.com)
