package liquibase.database.statement.generator;

import liquibase.database.Database;
import liquibase.database.HsqlDatabase;
import liquibase.database.H2Database;
import liquibase.database.statement.AddAutoIncrementStatement;
import liquibase.database.statement.syntax.Sql;
import liquibase.database.statement.syntax.UnparsedSql;
import liquibase.exception.LiquibaseException;
import liquibase.exception.JDBCException;

public class AddAutoIncrementGeneratorHsql extends AddAutoIncrementGenerator {

    public int getSpecializationLevel() {
        return SPECIALIZATION_LEVEL_DATABASE_SPECIFIC;
    }

    public boolean isValidGenerator(AddAutoIncrementStatement statement, Database database) {
        return database instanceof H2Database;
    }
    public Sql[] generateSql(AddAutoIncrementStatement statement, Database database) throws JDBCException {
        return new Sql[]{
                new UnparsedSql("ALTER TABLE " + database.escapeTableName(statement.getSchemaName(), statement.getTableName()) + " ALTER COLUMN " + database.escapeColumnName(statement.getSchemaName(), statement.getTableName(), statement.getColumnName()) + " " + statement.getColumnDataType() + " GENERATED BY DEFAULT AS IDENTITY IDENTITY")
        };
    }
}
