-- Snowflake Test Harness Environment Setup Script
-- This script creates the standard test environment expected by the Liquibase Test Harness
-- 
-- Run this script as ACCOUNTADMIN or a role with CREATE DATABASE privileges
-- =============================================================================

-- Create the standard test database expected by test harness
CREATE DATABASE IF NOT EXISTS LTHDB
    COMMENT = 'Liquibase Test Harness Database';

-- Use the database
USE DATABASE LTHDB;

-- Create a specific schema for test harness with a clear, descriptive name
CREATE SCHEMA IF NOT EXISTS TESTHARNESS
    DATA_RETENTION_TIME_IN_DAYS = 1
    COMMENT = 'Liquibase Test Harness Schema';

USE SCHEMA TESTHARNESS;

-- Create a specific role for test harness operations (required for object ownership)
CREATE ROLE IF NOT EXISTS LIQUIBASE_TEST_HARNESS_ROLE
    COMMENT = 'Role for Liquibase Test Harness operations';

-- Grant the role to the user
-- Replace 'COMMUNITYKEVIN' with your actual username if different
GRANT ROLE LIQUIBASE_TEST_HARNESS_ROLE TO USER COMMUNITYKEVIN;

-- Grant basic access to user
GRANT USAGE ON DATABASE LTHDB TO USER COMMUNITYKEVIN;
GRANT USAGE ON SCHEMA LTHDB.TESTHARNESS TO USER COMMUNITYKEVIN;

-- Grant permissions to the role (object creation must be done through roles, not directly to users)

GRANT USAGE ON DATABASE LTHDB TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT CREATE TABLE ON SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT CREATE VIEW ON SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT CREATE SEQUENCE ON SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT CREATE FUNCTION ON SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;

-- Grant future object permissions to the role
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS IN SCHEMA LTHDB.TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;

-- Grant account-level permissions for testing warehouse/database/schema operations
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;

-- Create a warehouse specifically for test harness to avoid conflicts
CREATE WAREHOUSE IF NOT EXISTS LTHDB_TEST_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'Dedicated warehouse for Liquibase Test Harness';

GRANT USAGE ON WAREHOUSE LTHDB_TEST_WH TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;

-- Create a warehouse specifically for test harness to avoid conflicts
CREATE WAREHOUSE IF NOT EXISTS XSMALL_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'Dedicated warehouse for Liquibase Test Harness';
GRANT USAGE ON WAREHOUSE XSMALL_WH TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;
-- Set the default role for the user (optional)
-- ALTER USER KEVINATLIQUIBASE SET DEFAULT_ROLE = LIQUIBASE_TEST_HARNESS_ROLE;

-- Verify the setup
SHOW DATABASES LIKE 'LTHDB';
SHOW SCHEMAS IN DATABASE LTHDB;

USE ROLE ACCOUNTADMIN;
GRANT ALL ON DATABASE LTHDB TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;