USE DATABASE LTHDB;
USE ROLE LIQUIBASE_TEST_HARNESS_ROLE;

-- Drop and recreate schema (this removes all objects in the schema)
DROP SCHEMA IF EXISTS TESTHARNESS CASCADE;
CREATE SCHEMA TESTHARNESS;

-- Ensure the role has proper permissions
GRANT ALL PRIVILEGES ON SCHEMA TESTHARNESS TO ROLE LIQUIBASE_TEST_HARNESS_ROLE;