-- Snowflake Test Harness Environment Setup Script
-- This script creates the standard test environment expected by the Liquibase Test Harness
-- 
-- Run this script as ACCOUNTADMIN or a role with CREATE DATABASE privileges
-- =============================================================================

-- Create the standard test database expected by test harness
CREATE DATABASE IF NOT EXISTS LB_DBEXT_INT_DB
    COMMENT = 'Liquibase Integration Database';

-- Use the database
USE DATABASE LB_DBEXT_INT_DB;

-- Create a specific schema for test harness with a clear, descriptive name
CREATE SCHEMA IF NOT EXISTS BASE_SCHEMA
    DATA_RETENTION_TIME_IN_DAYS = 1
    COMMENT = 'Liquibase Integration Test Schema';
CREATE SCHEMA IF NOT EXISTS ALT_SCHEMA
    DATA_RETENTION_TIME_IN_DAYS = 1
    COMMENT = 'Liquibase Integration Alt Schema';

USE SCHEMA BASE_SCHEMA;

-- Create a specific role for test harness operations (required for object ownership)
CREATE ROLE IF NOT EXISTS LB_INT_ROLE
    COMMENT = 'Role for Liquibase Integration Test operations';

-- Grant the role to the user
-- Replace 'COMMUNITYKEVIN' with your actual username if different
GRANT ROLE LB_INT_ROLE TO USER COMMUNITYKEVIN;

-- Grant basic access to user
GRANT USAGE ON DATABASE LB_DBEXT_INT_DB TO USER COMMUNITYKEVIN;
GRANT USAGE ON SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO USER COMMUNITYKEVIN;
GRANT USAGE ON SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO USER COMMUNITYKEVIN;

-- Grant permissions to the role (object creation must be done through roles, not directly to users)

GRANT USAGE ON DATABASE LB_DBEXT_INT_DB TO ROLE LB_INT_ROLE;

GRANT ALL PRIVILEGES ON SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;
GRANT CREATE TABLE ON SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;
GRANT CREATE VIEW ON SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;
GRANT CREATE SEQUENCE ON SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;
GRANT CREATE FUNCTION ON SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;

GRANT ALL PRIVILEGES ON SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;
GRANT CREATE TABLE ON SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;
GRANT CREATE VIEW ON SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;
GRANT CREATE SEQUENCE ON SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;
GRANT CREATE FUNCTION ON SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;

-- Grant future object permissions to the role
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS IN SCHEMA LB_DBEXT_INT_DB.BASE_SCHEMA TO ROLE LB_INT_ROLE;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS IN SCHEMA LB_DBEXT_INT_DB.ALT_SCHEMA TO ROLE LB_INT_ROLE;

-- Grant account-level permissions for testing warehouse/database/schema operations
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE LB_INT_ROLE;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE LB_INT_ROLE;

USE ROLE ACCOUNTADMIN;
GRANT ALL ON DATABASE LB_DBEXT_INT_DB TO ROLE LB_INT_ROLE;

-- Verify the setup
SHOW DATABASES LIKE 'LB_DBEXT_INT_DB';
SHOW SCHEMAS IN DATABASE LB_DBEXT_INT_DB;
