package liquibase.sqlgenerator.core;

import java.math.BigInteger;

import org.junit.Test;

import liquibase.database.Database;
import liquibase.database.core.DB2Database;
import liquibase.database.core.H2Database;
import liquibase.database.core.HsqlDatabase;
import liquibase.test.TestContext;

public class AddAutoIncrementGeneratorDB2Test extends AddAutoIncrementGeneratorTest {

    public AddAutoIncrementGeneratorDB2Test() throws Exception {
    	super(new AddAutoIncrementGeneratorDB2());
    }

     @Override
    protected boolean shouldBeImplementation(Database database) {
        return database instanceof DB2Database;
    }

     @Test
     public void testAddAutoIncrement() throws Exception {
     	for (Database database : TestContext.getInstance().getAllDatabases()) {
     		if (database instanceof DB2Database) {
     			super.testAddAutoIncrementStatement(
     				database,
     				null,
     				null,
     				"ALTER TABLE CATALOG_NAME.TABLE_NAME ALTER COLUMN COLUMN_NAME SET GENERATED BY DEFAULT AS IDENTITY");
     		}
     	}
     }

     @Test
     public void testAddAutoIncrementStartWith() throws Exception {
     	for (Database database : TestContext.getInstance().getAllDatabases()) {
     		if (database instanceof DB2Database || database instanceof DB2Database) {
     			super.testAddAutoIncrementStatement(
     				database,
     				BigInteger.valueOf(2),
     				null,
     				"ALTER TABLE CATALOG_NAME.TABLE_NAME ALTER COLUMN COLUMN_NAME SET GENERATED BY DEFAULT AS IDENTITY (START WITH 2)");
     		}
     	}
     }
     
     @Test
     public void testAddAutoIncrementStartWithIncrementBy() throws Exception {
     	for (Database database : TestContext.getInstance().getAllDatabases()) {
     		if (database instanceof DB2Database || database instanceof DB2Database) {
     			super.testAddAutoIncrementStatement(
     				database,
     				BigInteger.valueOf(2), 
     				BigInteger.TEN,
     				"ALTER TABLE CATALOG_NAME.TABLE_NAME ALTER COLUMN COLUMN_NAME SET GENERATED BY DEFAULT AS IDENTITY (START WITH 2, INCREMENT BY 10)");
     		}
     	}
     }
}