-- Database: hsqldb
-- Change Parameter: columnDataType=int
-- Change Parameter: columnName=id
-- Change Parameter: tableName=person
ALTER TABLE person ALTER COLUMN id int GENERATED BY DEFAULT AS IDENTITY;
