-- Database: unsupported
-- Change Parameter: columnDataType=int
-- Change Parameter: columnName=id
-- Change Parameter: tableName=person
ALTER TABLE person MODIFY id INT GENERATED BY DEFAULT AS IDENTITY;
