FROM liquibase/liquibase:latest

USER root

RUN apt-get update -y && \
  apt-get install --no-install-recommends -y unzip && \
  rm -rf /var/lib/apt/lists/*

RUN wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O "awscliv2.zip" && \
  unzip awscliv2.zip && rm -rf awscliv2.zip && \
  ./aws/install

USER liquibase
