name: Build & Deploy BigQuery extensions

on:
  workflow_call:
    inputs:
      liquibase-version:
        description: 'liquibase version'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      liquibase-version:
        description: 'liquibase version'
        required: true
        type: string

env:
  MAVEN_VERSION: '3.9.2'

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    continue-on-error: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout liquibase-bigquery
        with:
          repository: liquibase/liquibase-bigquery
          ref: main
          token: ${{ secrets.BOT_TOKEN }}
          path: liquibase-bigquery

      - uses: actions/checkout@v4
        name: Checkout liquibase-commercial-bigquery
        with:
          repository: liquibase/liquibase-commercial-bigquery
          ref: main
          token: ${{ secrets.BOT_TOKEN }}
          path: liquibase-commercial-bigquery

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: ${{ env.MAVEN_VERSION }}

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: |
            [
              {
                "id": "liquibase",
                "url": "https://maven.pkg.github.com/liquibase/liquibase",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              },
              {
                "id": "liquibase-pro",
                "url": "https://maven.pkg.github.com/liquibase/liquibase-pro",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              }
            ]
          servers: |
            [
              {
                "id": "liquibase",
                "username": "liquibot",
                "password": "${{ secrets.LIQUIBOT_PAT_GPM_ACCESS }}"
              },
              {
                "id": "liquibase-pro",
                "username": "liquibot",
                "password": "${{ secrets.LIQUIBOT_PAT_GPM_ACCESS }}"
              }
            ]

      - name: Re-version extensions
        run: |
          cd liquibase-bigquery
          mvn versions:set -DnewVersion=${{ inputs.liquibase-version }}
          cd ..
          cd liquibase-commercial-bigquery
          mvn versions:set -DnewVersion=${{ inputs.liquibase-version }}
          cd ..
          
      - name: Build and install
        run: |
          cd liquibase-bigquery
          mvn clean package -DskipTests
          cd ..
          cd liquibase-commercial-bigquery
          mvn clean package -DskipTests
          cd ..

      - name: Deploy to GitHub Packages
        continue-on-error: true
        run: |
          cd liquibase-bigquery
          OUTPUT=$(mvn deploy:deploy-file -Dfile=./target/liquibase-bigquery-${{ inputs.liquibase-version }}.jar -DpomFile=pom.xml -DrepositoryId=liquibase -Durl=https://maven.pkg.github.com/liquibase/liquibase-bigquery | tee /dev/fd/2)
          echo "$OUTPUT" | grep -q "status code: 409, reason phrase: Conflict (409)" && echo "liquibase-bigquery ${{ inputs.liquibase-version }} is already deployed in GitHub Packages"
          cd ..
          cd liquibase-commercial-bigquery
          OUTPUT=$(mvn deploy:deploy-file -Dfile=./target/liquibase-commercial-bigquery-${{ inputs.liquibase-version }}.jar -DpomFile=pom.xml -DrepositoryId=liquibase-pro -Durl=https://maven.pkg.github.com/liquibase/liquibase-pro | tee /dev/fd/2)
          echo "$OUTPUT" | grep -q "status code: 409, reason phrase: Conflict (409)" && echo "liquibase-commercial-bigquery ${{ inputs.liquibase-version }} is already deployed in GitHub Packages"
          cd ..
