name: Build & Deploy BigQuery extensions

on:
  workflow_call:
    inputs:
      liquibase-version:
        description: 'liquibase version'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      liquibase-version:
        description: 'liquibase version'
        required: true
        type: string

env:
  MAVEN_VERSION: '3.9.2'

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout liquibase-bigquery
        with:
          repository: liquibase/liquibase-bigquery
          ref: main
          token: ${{ secrets.BOT_TOKEN }}
          path: liquibase-bigquery
          
      - uses: actions/checkout@v4
        name: Checkout liquibase-commercial-bigquery
        with:
          repository: liquibase/liquibase-bigquery
          ref: main
          token: ${{ secrets.BOT_TOKEN }}
          path: liquibase-commercial-bigquery

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: ${{ env.MAVEN_VERSION }}

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: |
            [
              {
                "id": "liquibase",
                "url": "https://maven.pkg.github.com/liquibase/liquibase",
                "releases": {
                  "enabled": "false"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              },
              {
                "id": "liquibase-pro",
                "url": "https://maven.pkg.github.com/liquibase/liquibase-pro",
                "releases": {
                  "enabled": "false"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              },
              {
                "id": "liquibase-bigquery",
                "url": "https://maven.pkg.github.com/liquibase/liquibase-bigquery",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              },
              {
                "id": "liquibase-bigquery-commercial",
                "url": "https://maven.pkg.github.com/liquibase/liquibase-bigquery-commercial",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              }
            ]
          servers: |
            [
              {
                "id": "liquibase",
                "username": "liquibot",
                "password": "${{ secrets.LIQUIBOT_PAT }}"
              },
              {
                "id": "liquibase-pro",
                "username": "liquibot",
                "password": "${{ secrets.LIQUIBOT_PAT }}"
              },
              {
                "id": "liquibase-bigquery",
                "username": "liquibot",
                "password": "${{ secrets.LIQUIBOT_PAT }}"
              },
              {
                "id": "liquibase-bigquery-commercial",
                "username": "liquibot",
                "password": "${{ secrets.LIQUIBOT_PAT }}"
              }
            ]

      - name: Re-version BigQuery extensions
        run: |
          cd liquibase-bigquery
          mvn versions:set -DnewVersion=${{ inputs.liquibase-version }}
          cd ..
          cd liquibase-commercial-bigquery
          mvn versions:set -DnewVersion=${{ inputs.liquibase-version  }}
          cd ..
          
      - name: Build and install BigQuery extensions
        run: |
          cd liquibase-bigquery
          mvn clean package -DskipTests
          cd ..
          cd liquibase-commercial-bigquery
          mvn clean package -DskipTests
          cd ..

      - name: Deploy BigQuery extensions to GitHub Packages
        env:
          MAVEN_USERNAME: liquibot
          MAVEN_PASSWORD: ${{ secrets.LIQUIBOT_PAT }}
        run: |
          cd liquibase-bigquery
          mvn deploy:deploy-file -Dfile=./target/liquibase-bigquery-${{ inputs.liquibase-version }}.jar -DpomFile=pom.xml -DrepositoryId=liquibase-bigquery -Durl=https://maven.pkg.github.com/liquibase/liquibase-bigquery -Dtoken=${{ secrets.BOT_TOKEN }}
          cd ..
          cd liquibase-commercial-bigquery
          mvn deploy:deploy-file -Dfile=./target/liquibase-bigquery-commercial-${{ inputs.liquibase-version }}.jar -DpomFile=pom.xml -DrepositoryId=liquibase-bigquery-commercial -Durl=https://maven.pkg.github.com/liquibase/liquibase-bigquery-commercial -Dtoken=${{ secrets.BOT_TOKEN }}
          cd ..
