name: Build BigQuery jars

on:
  workflow_call:
    inputs:
      liquibase-version:
        description: 'liquibase version'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      liquibase-version:
        description: 'liquibase version'
        required: true
        type: string

env:
  MAVEN_VERSION: '3.9.2'

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout liquibase-bigquery
        with:
          repository: liquibase/liquibase-bigquery
          ref: main
          token: ${{ secrets.BOT_TOKEN }}
          path: liquibase-bigquery
          
      - uses: actions/checkout@v4
        name: Checkout liquibase-commercial-bigquery
        with:
          repository: liquibase/liquibase-bigquery
          ref: main
          token: ${{ secrets.BOT_TOKEN }}
          path: liquibase-commercial-bigquery

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: ${{ env.MAVEN_VERSION }}

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: |
            [
              {
                "id": "liquibase",
                "url": "https://maven.pkg.github.com/liquibase/liquibase",
                "releases": {
                  "enabled": "false"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              },
              {
                "id": "liquibase-pro",
                "url": "https://maven.pkg.github.com/liquibase/liquibase-pro",
                "releases": {
                  "enabled": "false"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              },
              {
                "id": "liquibase-bigquery",
                "url": "https://maven.pkg.github.com/liquibase/liquibase-bigquery",
                "releases": {
                  "enabled": "false"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              },
              {
                "id": "liquibase-commercial-bigquery",
                "url": "https://maven.pkg.github.com/liquibase/liquibase-commercial-bigquery",
                "releases": {
                  "enabled": "false"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              }
            ]
          servers: |
            [
              {
                "id": "liquibase",
                "username": "liquibot",
                "password": "${{ secrets.LIQUIBOT_PAT }}"
              },
              {
                "id": "liquibase-pro",
                "username": "liquibot",
                "password": "${{ secrets.LIQUIBOT_PAT }}"
              },
              {
                "id": "file-replacer-maven-plugin",
                "username": "liquibot",
                "password": "${{ secrets.LIQUIBOT_PAT }}"
              },
              {
                "id": "liquibase-bigquery",
                "username": "liquibot",
                "password": "${{ secrets.LIQUIBOT_PAT }}"
              },
              {
                "id": "liquibase-commercial-bigquery",
                "username": "liquibot",
                "password": "${{ secrets.LIQUIBOT_PAT }}"
              }
            ]

      - name: Re-version BigQuery extensions
        run: |
          cd liquibase-bigquery
          mvn versions:set -DnewVersion=${{ inputs.liquibase-version }}
          cd ..
          cd liquibase-commercial-bigquery
          mvn versions:set -DnewVersion=${{ inputs.liquibase-version  }}
          cd ..
          
      - name: Build and install BigQuery extensions
        run: |
          cd liquibase-bigquery
          mvn clean install -DskipTests
          cd ..
          cd liquibase-commercial-bigquery
          mvn clean install -DskipTests
          cd ..

      - name: Add temporal distributionManagement to pom.xml
        run: |
          python3 -c "
          import xml.etree.ElementTree as ET
          for pom_file in ['liquibase-bigquery/pom.xml', 'liquibase-commercial-bigquery/pom.xml']:
              tree = ET.parse(pom_file)
              root = tree.getroot()
              ns = {'mvn': 'http://maven.apache.org/POM/4.0.0'}
              ET.register_namespace('', ns['mvn'])
              distributionManagement = ET.SubElement(root, 'distributionManagement')
              repository = ET.SubElement(distributionManagement, 'repository')
              ET.SubElement(repository, 'id').text = pom_file.split('/')[0]
              ET.SubElement(repository, 'name').text = 'GitHub liquibase Apache Maven Packages'
              ET.SubElement(repository, 'url').text = f'https://maven.pkg.github.com/liquibase/{pom_file.split('/')[0]}'
              tree.write(pom_file)
          "

      - name: Deploy BigQuery extensions to GitHub Packages
        run: |
          cd liquibase-bigquery
          mvn deploy -DskipTests -DrepositoryId=liquibase-bigquery
          cd ..
          cd liquibase-commercial-bigquery
          mvn deploy -DskipTests -DrepositoryId=liquibase-commercial-bigquery
          cd ..
