name: OWASP Scanner

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to scan'
        required: true
        type: string
      component:
        description: 'Artifact component'
        required: false
        type: string
        default: 'liquibase'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to scan'
        required: true
        type: string
      component:
        description: 'Artifact component'
        required: true
        type: string
        default: 'liquibase/liquibase'


jobs:
  scan:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          repository: ${{ inputs.component }}

      - name: Run the scanner
        id: run_owasp
        run: mvn clean org.owasp:dependency-check-maven:aggregate -Dodc.outputDirectory=. -Dodc.nvdApiKey=${{ secrets.NVD_API_KEY }} -Dodc.failOnError=true
    
      - name: Upload OWASP Dependency-Check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: owasp-dependency-check
            path: ./dependency-check-report.html
  