# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Package

on:
  workflow_run:
    workflows: ["Build and Test"]
    branches: [unversioned-master]
    types:
      - completed

jobs:
  package:
    name: Build Packages
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Create Check
        id: create-check
        uses: actions/github-script@v4
        with:
          script: |
            const check = await github.checks.create({
              "owner": "liquibase",
              "repo": "liquibase",
              "name": "Build Packages",
              "head_sha": "${{ github.event.workflow_run.head_sha }}",
              "status": "in_progress",
              "details_url": "https://github.com/liquibase/liquibase/actions/runs/${{ github.run_id }}"
            });
            core.setOutput("checkId", check.data.id);

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Download liquibase modules
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: ${{ github.event.workflow_run.head_branch }}
          name: liquibase-modules
          path: download

      - name: Install Built Modules
        run: |
          (cd download && find . -name *-SNAPSHOT.jar -exec mvn -B org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file -Dfile={} \;)
          (cd download && find . -name *-SNAPSHOT-sources.jar -exec mvn -B org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file -Dfile={} \;)

      - name: Build Final Jar & Tar/Zips
        run: mvn -B -pl liquibase-dist package

      - name: Archive Packages
        uses: actions/upload-artifact@v2
        with:
          name: liquibase-packages
          path: |
            liquibase-dist/target/liquibase-0-SNAPSHOT.tar.gz
            liquibase-dist/target/liquibase-0-SNAPSHOT.zip
            liquibase-dist/target/liquibase-0-SNAPSHOT.jar
            liquibase-maven-plugin/target/liquibase-maven-plugin-0-SNAPSHOT.jar
            liquibase-cdi/target/liquibase-cdi-0-SNAPSHOT.jar

      - name: Report Check
        uses: actions/github-script@v4
        if: always()
        with:
          script: |
            github.checks.update({
              "owner": "liquibase",
              "repo": "liquibase",
              "check_run_id": ${{ steps.create-check.outputs.checkId }},
              "status": "completed",
              "conclusion": "${{ job.status }}",
              "details_url": "https://github.com/liquibase/liquibase/actions/runs/${{ github.run_id }}",
            });
