name: Release Docker

run-name: "Release Docker Images - v${{ inputs.version }}${{ inputs.dry_run && ' (Dry Run)' || '' }}"

on:
  workflow_call:
    inputs:
      version:
        description: "Version to release"
        required: true
        type: string
      dry_run:
        description: "Flag to indicate if this is a dry-run"
        required: false
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        type: string
      dry_run:
        description: "Flag to indicate if this is a dry-run"
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write

jobs:
  release-docker:
    name: Release docker images
    uses: ./.github/workflows/docker-release.yml
    permissions:
      contents: read
      id-token: write
    with:
      liquibaseVersion: ${{ inputs.version }}
      dryRun: ${{ inputs.dry_run || false }}
    secrets: inherit
