name: Release Deploy XSD

run-name: "Deploy XSD Files - v${{ inputs.version }}${{ inputs.dry_run && ' (Dry Run)' || '' }}"

on:
  workflow_call:
    inputs:
      version:
        description: "Version to deploy"
        required: true
        type: string
      dry_run:
        description: "Flag to indicate if this is a dry-run"
        required: false
        type: boolean
        default: false
  
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy"
        required: true
        type: string
      dry_run:
        description: "Flag to indicate if this is a dry-run"
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write

jobs:
  deploy-xsd:
    name: Upload xsds
    runs-on: ubuntu-22.04
    if: ${{ inputs.dry_run == false }}
    steps:
      - name: Download liquibase xsd
        uses: actions/checkout@v5
        with:
          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: liquibase-core-repo
          repository: "liquibase/liquibase"

      - name: Configure AWS credentials for vault access
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.LIQUIBASE_VAULT_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Get secrets from vault
        id: vault-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,/vault/liquibase
          parse-json-secrets: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.AWS_PROD_GITHUB_OIDC_ROLE_ARN_BUILD_LOGIC }}
          aws-region: us-east-1

      - name: Upload to s3
        # aws s3 sync syncs directories and S3 prefixes.
        run: |
          aws s3 sync liquibase-core-repo/liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/ s3://liquibaseorg-origin/xml/ns/dbchangelog/ --content-type application/octet-stream --only-show-errors

      - name: Index.htm file upload
        # get the major.minor xsd version. grab the index.htm from s3, add the new verison of xsd and sync with the s3 again
        run: |
          version=${{ inputs.version }}
          arr=(${version//./ })
          xsd_version=${arr[0]}"."${arr[1]}
          mkdir index-file
          aws s3 cp s3://liquibaseorg-origin/xml/ns/dbchangelog/index.htm index-file
          if ! grep -q ${xsd_version} index-file/index.htm ; then
            sed -ie "s/<\/ul>/  <li><a href=\"\/xml\/ns\/dbchangelog\/dbchangelog-${xsd_version}.xsd\">dbchangelog-${xsd_version}.xsd<\/a><\/li>\n<\/ul>/" index-file/index.htm
            aws s3 sync index-file s3://liquibaseorg-origin/xml/ns/dbchangelog/ --only-show-errors
          fi

      - name: Liquibase xsds SFTP upload
        uses: wangyucode/sftp-upload-action@v2.0.4
        with:
          host: ${{ env.WPENGINE_SFTP_HOST }}
          port: ${{ env.WPENGINE_SFTP_PORT }}
          username: ${{ env.WPENGINE_SFTP_USER }}
          password: ${{ env.WPENGINE_SFTP_PASSWORD }}
          compress: true
          forceUpload: true
          localDir: "liquibase-core-repo/liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/"
          remoteDir: "/xml/ns/dbchangelog/"

      - name: Liquibase index.htm SFTP upload
        uses: wangyucode/sftp-upload-action@v2.0.4
        with:
          host: ${{ env.WPENGINE_SFTP_HOST }}
          port: ${{ env.WPENGINE_SFTP_PORT }}
          username: ${{ env.WPENGINE_SFTP_USER }}
          password: ${{ env.WPENGINE_SFTP_PASSWORD }}
          compress: false
          forceUpload: true
          localDir: "index-file/"
          remoteDir: "/xml/ns/dbchangelog/"
