name: Release Manual Approval

run-name: "Manual Approval - v${{ inputs.version }}"

on:
  workflow_call:
    inputs:
      version:
        description: "Version to approve for deployment"
        required: true
        type: string
      dry_run:
        description: "Flag to indicate if this is a dry-run release"
        required: false
        type: boolean
        default: false
  
  workflow_dispatch:
    inputs:
      version:
        description: "Version to approve for deployment"
        required: true
        type: string
      dry_run:
        description: "Flag to indicate if this is a dry-run release"
        required: false
        type: boolean
        default: false

permissions:
  issues: write
  pull-requests: write

jobs:
  manual-approval:
    name: Request Manual Approval
    runs-on: ubuntu-22.04
    if: ${{ inputs.dry_run == false }}
    steps:
      - name: Get Version to deploy
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: filipelautert,rberezen,jnewton03,kristyldatical,sayaliM0412
          minimum-approvals: 2
          issue-title: "Deploying ${{ inputs.version }} to Maven Central"
          issue-body: "Please approve or deny the deployment of version ${{ inputs.version }} to Maven Central"
          additional-approved-words: "lgtm,✅,👍,proceed,shipit,:shipit:"
          additional-denied-words: "stop,error,failed,fail,broken,:x:,👎"
