name: Run Pro build & tests

on:
  workflow_call:
    inputs:
      latestMergeSha:
        description: 'Latest Merge sha of OSS PR'
        required: false
        default: ''
        type: string
      thisBranchName:
        description: 'Branch Name of OSS PR'
        required: false
        default: ''
        type: string
  pull_request_target:
    types: [labeled]

permissions:
  id-token: write # Required for OIDC authentication with AWS

jobs:
  # build and test pro master branch using current branch to ensure nothing is being broken by this PR
  run-pro-build:
    name: Build & Test Pro
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'build&TestPro') || (github.event_name != 'pull_request' && github.event_name != 'pull_request_target')
    steps:

      - name: Check variables
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event.pull_request.labels.*.name: ${{ contains(github.event.pull_request.labels.*.name, 'build&TestPro') }}"
          echo "github.event.after: ${{ github.event.after }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.event.pull_request.merged: ${{ github.event.pull_request.merged }}"
          echo "github.event_name: ${{ github.event_name }}"

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.after}} # get the sha of the commit or the new commit created when branch is merged to master

  run-pro-build-and-tests:
    runs-on: ubuntu-latest
    needs: [run-pro-build ]
    name: Trigger Pro build
    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables for PR branch and SHA
        run: |
          if [ "${{ github.event_name }}" == "workflow_call" ]; then
            echo "RUN_TESTS_BRANCH=${{ inputs.thisBranchName }}" >> $GITHUB_ENV
            echo "RUN_TESTS_SHA=${{ inputs.latestMergeSha }}" >> $GITHUB_ENV
          else
            echo "RUN_TESTS_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
            echo "RUN_TESTS_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          fi

      - name: Get OSS Workflow Run URL
        id: get-workflow-url
        run: |
          repo_url="https://github.com/${{ github.repository }}"
          ossWorkflowUrl="${repo_url}/actions/runs/${{ github.run_id }}"
          echo "ossWorkflowUrl=${ossWorkflowUrl}" >> $GITHUB_ENV

      - name: Configure AWS credentials for vault access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.LIQUIBASE_VAULT_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Get secrets from vault
        id: vault-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,/vault/liquibase
          parse-json-secrets: true

      - name: Get GitHub App token
        id: get-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ env.LIQUIBASE_GITHUB_APP_ID }}
          private-key: ${{ env.LIQUIBASE_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          permission-contents: write
          permission-actions: write

      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v2
        id: return_dispatch
        with:
          token: ${{ steps.get-token.outputs.token }}
          ref: "master"
          repo: liquibase-pro
          owner: liquibase
          workflow: build-and-test-from-oss.yml
          workflow_inputs:
            '{"liquibaseCommit": "${{ env.RUN_TESTS_SHA }}",
                "runDescription": "${{ env.ossWorkflowUrl }}",
                "liquibaseBranch": "${{ env.RUN_TESTS_BRANCH }}"
              }'

      - name: Display run ID and URL
        run: |
          echo ${{steps.return_dispatch.outputs.run_id}}
          echo ${{steps.return_dispatch.outputs.run_url}}

      - name: Report PRO Build & Tests Run URL
        uses: actions/github-script@v7
        with:
          script: |
            const targetURL = "https://github.com/liquibase/liquibase-pro/actions/runs/${{ steps.return_dispatch.outputs.run_id }}"
            core.notice("Pro Build & Tests Run URL: " + targetURL);
