
name: Liquibase Url Prerequisites Check

# Job will run nightly at 02:10 EDT / 01:10 CDT
# Time below is UTC
on:
  schedule:
    - cron: "10 6 * * *"
  workflow_dispatch:

jobs:
  urlcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check URLs
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          args: --verbose --timeout 5 --max-retries 2 .github/workflows/url-test.md
          fail: true

      - name: Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2
        env:
          SLACK_CHANNEL: team-liquibase-foundation
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_MESSAGE: "${{ github.job }}: ${{ job.status }} @here"
          SLACK_USERNAME: "liquibot"
          SLACK_WEBHOOK: ${{ secrets.SNYK_LIQUIBASE_SLACK_WEBHOOK }}
          MSG_MINIMAL: actions url
          SLACK_ICON_EMOJI: ':liquibase:'
          SLACK_LINK_NAMES: true
          
