name: Weekly Integration Tests

permissions:
  contents: read
  id-token: write
  packages: write
  actions: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0'

jobs:

  deploy-ephemeral-cloud-infra:
    uses: liquibase/build-logic/.github/workflows/ephemeral-cloud-infra.yml@main
    secrets: inherit
    with:
        deploy: true
        snowflake_oss: true

  snowflake-its:
    name: Run Snowflake Cloud integration tests
    needs: deploy-ephemeral-cloud-infra
    timeout-minutes: 240
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cp .github/maven/settings-snapshots.xml ~/.m2/settings.xml
          echo "MAVEN_GPM_PASSWORD=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Configure AWS credentials for vault access
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: ${{ secrets.LIQUIBASE_VAULT_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Get secrets from vault
        id: vault-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@2cb1a461cbd4865ac4299648312e4704c646cd53 # v3.0.1
        with:
          secret-ids: |
            ,/vault/liquibase
          parse-json-secrets: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
            role-to-assume: ${{ env.AWS_DEV_GITHUB_OIDC_ROLE_ARN_BUILD_LOGIC }}
            aws-region: us-east-1

      - name: Get LIQUIBASEOSS secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@2cb1a461cbd4865ac4299648312e4704c646cd53 # v3.0.1
        with:
          secret-ids: |
            LIQUIBASEOSS_USERNAME, liquibaseoss_usrname
            LIQUIBASEOSS_PASSWORD, liquibaseoss_pwd

      - name: Run tests
        run: |
          ./mvnw -B "-DtrimStackTrace=false" \
            "-Dliquibase.sdk.testSystem.test=snowflake" \
            "-Dliquibase.sdk.testSystem.snowflake.url=jdbc:${{ env.LIQUIBASEOSS_URL }}&schema=PUBLIC&db=LIQUIBASEOSS" \
            "-Dliquibase.sdk.testSystem.snowflake.username=${{ env.LIQUIBASEOSS_USERNAME }}" \
            "-Dliquibase.sdk.testSystem.snowflake.password=${{ env.LIQUIBASEOSS_PASSWORD }}" \
            "-Dtest=*IntegrationTest,*ExecutorTest" \
            "-DfailIfNoTests=false" \
            "-Dsurefire.failIfNoSpecifiedTests=false" \
            "-Dsurefire.failIfNoTests=false" \
            clean verify

      - name: Archive Test Results
        if: ${{ inputs.archive_test_results == 'true' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: liquibase-test-results-snowflake
          path: |
            ./**/target/surefire-reports
            ./**/target/site

  get-stack-id:
    if: always()
    needs: [ deploy-ephemeral-cloud-infra, snowflake-its ]
    runs-on: ubuntu-latest
    outputs:
      stack-id: ${{ steps.get-stack-id.outputs.stack-id }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Get Stack ID
        id: get-stack-id
        uses: ./.github/actions/get-stack-id
        with:
          stack-id: ${{ needs.deploy-ephemeral-cloud-infra.outputs.stack_id }}
          run-id: ${{ github.run_id }}

  destroy-ephemeral-cloud-infra:
    if: always()
    needs: [ deploy-ephemeral-cloud-infra, snowflake-its, get-stack-id ]
    uses: liquibase/build-logic/.github/workflows/ephemeral-cloud-infra.yml@main
    secrets: inherit
    with:
        destroy: true
        stack_id: ${{ needs.get-stack-id.outputs.stack-id }}
        snowflake_oss: true

  run-slack-notification:
    runs-on: ubuntu-latest
    if: failure()
    needs: [ snowflake-its ]
    steps:
      - name: Dispatch event to build-logic repository
        id: weekly-integration-tests
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: liquibase/build-logic
          event-type: test-failure       
          client-payload: '{"repository": "${{ github.repository }}", "branch": "${{ github.ref }}", "sha": "${{ github.sha }}", "server_url": "${{ github.server_url }}", "run_id": "${{ github.run_id }}", "workflow_name": "${{ github.action }}"}'

